name: biblio

description: A cross-platform mobileapp to keep track of your books.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+2

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: any
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.0.0
  sembast: ^3.8.0+1
  simple_barcode_scanner: ^0.2.5
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
