environment:
  DIGITALOCEAN_WEBSECURE_TOKEN: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
  GOOGLE_BOOKS_API_TOKEN: "${GOOGLE_BOOKS_API_TOKEN}"
  ISBNDB_API_KEY: "${ISBNDB_API_KEY}"
  MONGO_DBNAME: "${MONGO_DBNAME}"
  MONGO_URL: "${MONGO_URL}"

packages:
  - name: auth
    functions:
      - name: sendOtp
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
      - name: verifyOtp
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
  - name: books
    functions:
      - name: getBookByIsbn
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
      - name: searchBooks
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
  - name: libraries
    functions:
      - name: createLibrary
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
      - name: getLibraries
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
      - name: updateLibrary
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
      - name: deleteLibrary
        runtime: go:1.25
        limits:
          timeout: 5000
          memory: 256
        web: true
        webSecure: "${DIGITALOCEAN_WEBSECURE_TOKEN}"
