name: tsunbooku

description: Tsunbooku — a mobile app to keep track of your books.

publish_to: 'none'

version: 0.4.0+11

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.3.0
  flutter_dotenv: ^6.0.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: any
  newrelic_mobile: ^1.2.9
  path: ^1.9.0
  path_provider: ^2.1.6
  provider: ^6.0.0
  sembast: ^3.8.9+1
  shared_preferences: ^2.5.5
  mobile_scanner: ^7.2.1
  package_info_plus: ^10.2.1
  sqflite: ^2.4.3  
  uuid: ^4.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.4.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
