name: Backend Checks

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        go-version: ["1.25"]
        mongodb-version: ["8.0"]
        dir:
          - backend/packages/auth/sendOtp
          - backend/packages/auth/verifyOtp
          - backend/packages/books/getBookByIsbn
          - backend/packages/books/searchBooks
          - backend/packages/libraries/createLibrary
          - backend/packages/libraries/getLibraries
          - backend/packages/libraries/updateLibrary
          - backend/packages/libraries/deleteLibrary
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs
          mongodb-port: 27017
      - name: Lint and Test
        working-directory: ${{ matrix.dir }}
        run: |
          export MONGO_DBNAME=db
          export MONGO_URL=mongodb://localhost:27017
          go get .
          go mod tidy
          go test
      - name: Test build
        working-directory: ${{ matrix.dir }}
        run: |
          go build .

  sam-build:
    name: AWS SAM build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: SAM build and validate
        run: |
          make build-all
          sam build
          sam validate