name: Backend Publish

on:
  push:
    tags:
      - 'backend-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: SAM build and validate
        run: |
          make build-all
          sam build
          sam validate
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name biblio-api \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --parameter-overrides \
              MongoUrl=${{ secrets.MONGO_URL }} \
              MongoDbname=${{ secrets.MONGO_DBNAME }} \
              GoogleBooksApiToken=${{ secrets.GOOGLE_BOOKS_API_TOKEN }} \
              IsbnDbApiKey=${{ secrets.ISBNDB_API_KEY }}
