name: Backend Publish

on:
  push:
    tags:
      - 'backend-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Create .env file
        run: |
          touch .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "DIGITALOCEAN_WEBSECURE_TOKEN=${{ secrets.DIGITALOCEAN_WEBSECURE_TOKEN }}" >> .env
          echo "GOOGLE_BOOKS_API_TOKEN=${{ secrets.GOOGLE_BOOKS_API_TOKEN }}" >> .env
          echo "ISBNDB_API_KEY=${{ secrets.ISBNDB_API_KEY }}" >> .env
          echo "MONGO_DBNAME=${{ secrets.MONGO_DBNAME }}" >> .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
      - name: Publish
        run: |
          doctl serverless install
          doctl serverless connect ${{ vars.DIGITALOCEAN_LABEL }} \
            -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          doctl serverless deploy .
          doctl serverless functions invoke books/getBookByIsbn -p isbn:9780735619678
