name: Android Instrumentation Test

on: [pull_request]

jobs:
  android_test:
     name: Test on Android
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: Nexus 4
          emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            ./gradlew connectedAndroidTest --continue
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: '**/build/reports/androidTests/connected/'
